#!/usr/bin/env bash

status() {
  printf "  [ \033[00;34m..\033[0m ] $1\n"
}

info() {
  printf "  \033[00;34m$1\033[0m\n"
}

section() {
  echo
  info "$@"
}

success() {
  printf "\r\033[2K  [ \033[00;32mOK\033[0m ] $1\n"
}

fail () {
  printf "\r\033[2K  [\033[0;31mFAIL\033[0m] $1\n"
  echo ''
}

export -f status
export -f info
export -f section
export -f success
export -f fail
