#!/usr/bin/env bash

# Load user's environment
if [ -f $HOME/.zshrc ]; then
  source $HOME/.zshrc >/dev/null 2>&1
fi

# Install packages
for installer in $(find . -name "*.installer"); do
  $installer
done


# Symlink all *.symlink files
for f in $(find . -name "*.symlink"); do
  FILENAME=$(basename $f);
  RELATIVEPATH=$(echo $f | sed 's/.\///')
  TARGETNAME=$(echo $FILENAME | sed 's/.symlink$//g')
  echo "Linking $TARGETNAME"
  FULLPATH="$PWD/$RELATIVEPATH";
  ln -nfs $FULLPATH "$HOME/.$TARGETNAME"
done


# Custom linking
for f in $(find . -name "*.customlink"); do
  FILENAME=$(basename $f);
  RELATIVEPATH=$(echo $f | sed 's/.\///')
  TARGETNAME=$(echo $FILENAME | sed 's/.customlink$//g')
  echo "Linking $TARGETNAME"
  FULLPATH="$PWD/$RELATIVEPATH";
  TARGETPATH=$(head -1 $RELATIVEPATH | sed 's/#//' | sed "s|^~|$HOME|")
  ln -nfs "$FULLPATH" "$TARGETPATH"
done

# Linking directories
for dir in $(find . -name "*.linkdir" -type d); do
  TARGET=$(cat $dir/_target | head -1 | sed "s|^~|$HOME|")
  DIRNAME=$(echo $dir | sed 's|\.linkdir$||' | sed 's|^./||')
  ln -nfs "$PWD/$dir" "$TARGET/$DIRNAME"
done

exit 0
