alias gpr="git pull --rebase"
alias gitpull="git pull && git submodule update --init --recursive && git submodule foreach git pull origin master"
alias gl="git log --graph --pretty=format:'%Cred%h%Creset %Cblue[%an]%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)%Creset' --abbrev-commit"

alias gp="git push"
alias ga="git add"
alias gd="git diff"
alias gr="git rebase"
alias g-="git checkout -"
alias gh="git show HEAD"
alias gca="git commit -a"
