alias g="git"

alias gpr="git pull --rebase"
alias gitpull="git pull && git submodule update --init --recursive && git submodule foreach git pull origin master"
alias gl="g l"

alias gp="git push"
alias ga="git add"
alias gd="git diff"
alias gdd="git diff -w --word-diff-regex=[^[:space:]]"
alias gr="git rebase"
alias g-="git checkout -"
alias gh="git show HEAD"
alias gca="git commit -a"
alias gc="git commit -v"
alias gs="git status"
alias gb="git branch"
