alias reload="source ~/.zshrc"
alias s="sparkfile --location ~/Dropbox/Sparkfile"
alias serve="python -m SimpleHTTPServer"
alias beam="open -a Beamer"
alias docker-compost="echo You meant docker-compose!! && echo && docker-compose"
